apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: NodePort       #svc类型  就算不指定默认也是ClusterIP
  selector:			   #匹配如下标签的pod来进行访问，匹配不到是访问不了的 这里起作用的就是selector(选择器)
    app: myapp
    release: stabel
  ports:
  - name: http
    port: 80            #前端访问端口
    targetPort: 80      #后端真实服务使用端口
